In [2]:
import numpy as np

# Array Slicing in Numpy and filtering

In [3]:
a = np.arange(1,10,dtype='int').reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a[2,2]

9

In [ ]:
a[0,2]

3

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[:,1]

array([2, 5, 8])

In [ ]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
a = np.arange(1,26,dtype="int").reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(a)
a[1:4,1:3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [ ]:
a[:,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])

In [ ]:
a[2:4,::2]

array([[11, 13, 15],
       [16, 18, 20]])

In [ ]:
a[4,0:3:2]

array([21, 23])

In [ ]:
a[0:3:2,1:3]

array([[ 2,  3],
       [12, 13]])

In [ ]:
a[1:5:2,1:5:2]

array([[ 7,  9],
       [17, 19]])

In [ ]:
a[::4,::4]

array([[ 1,  5],
       [21, 25]])

In [ ]:
a = np.arange(1,28,dtype = "int").reshape(3,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
a[2,1,1]

23

In [ ]:
a[0:3,1,1,2]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

# filtering

In [ ]:
a = np.arange(1,26,dtype="int").reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
a>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [ ]:
x = a[a>10]
print(x)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a<10] = 111
print(a)

[[111 111 111 111 111]
 [111 111 111 111  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


# random with numpy

In [ ]:
np.random.random(5)

array([0.15051877, 0.68243972, 0.31188145, 0.86682636, 0.97085903])

In [ ]:
np.random.random((3,3))

array([[0.11590896, 0.59671026, 0.4281133 ],
       [0.03203022, 0.22119142, 0.33157748],
       [0.29705178, 0.89275922, 0.31968894]])

In [ ]:
x = np.random.randint(45,66,(2,4,3))
print(x)

[[[49 45 57]
  [63 60 62]
  [63 64 53]
  [57 60 54]]

 [[51 65 49]
  [61 63 65]
  [51 62 62]
  [47 52 52]]]


In [ ]:
a = np.random.rand(3,3)          # np.random.rand is for Uniform Distribution (in the half-open interval [0.0,1.0))
print(a)

[[0.57846546 0.2097219  0.79512444]
 [0.24008421 0.96218295 0.33965888]
 [0.36527879 0.64191915 0.77216393]]


In [ ]:
a = np.random.randn(3,3)    # np.random.randn is for Standard Normal(Gaussian Distribution) Distribution (mean 0 and variance 1)
print(a)

[[-3.04101896  0.157455    0.25948281]
 [ 2.00458399  0.06927897 -0.69486625]
 [ 1.30592752  0.71968007  0.31348947]]


In [ ]:
x = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
np.random.choice(x)

15

In [ ]:
x = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
np.random.permutation(x)

array([ 4,  6, 11, 13,  7,  2,  3,  9, 14, 15,  1,  8, 10, 12,  5])

# np.char

In [ ]:
a = "Hello i am from India"
b = np.char.upper(a)
print(b)

HELLO I AM FROM INDIA


In [ ]:
a = "Hello i am from India"
b = np.char.lower(a)
print(b)

hello i am from india


In [ ]:
a = "Hello i am from India"               #IMP
b = np.char.replace(a,"India","USA")
print(b)

Hello i am from USA


In [ ]:
a = "Hello i am from India "             #IMP
b = "I love my india"
c = np.char.add(a,b)
print(c)

Hello i am from India I love my india


In [ ]:
a = "hello i am from india"
b = np.char.center(a,60)
print(b)

                   hello i am from india                    


In [ ]:
a = "hello i am from india"
b = np.char.center(a,60,fillchar="-")
print(b)

-------------------hello i am from india--------------------


In [ ]:
a = "Hello how are you?"
b = "india"
np.char.join([":", "/"], [a,b])

array(['H:e:l:l:o: :h:o:w: :a:r:e: :y:o:u:?', 'i/n/d/i/a'], dtype='<U35')

In [ ]:
np.char.split(a)

array(list(['Hello', 'how', 'are', 'you?']), dtype=object)

In [ ]:
np.char.splitlines("hello\nIndian")

array(list(['hello', 'Indian']), dtype=object)

In [ ]:
np.char.equal(a,b)

array(False)

# datetime with numpy

In [ ]:
today = np.datetime64("2022-11-12")
print(today)
print(type(today))

2022-11-12
<class 'numpy.datetime64'>


In [ ]:
today = np.datetime64("2022-11-12",'Y')
print(today)

2022


In [ ]:
today = np.datetime64("2022-11-12",'M')
print(today)

2022-11


In [ ]:
diff = np.datetime64("2022-11-12") - np.datetime64("2020-11-12")
print(diff)

730 days


In [ ]:
x = np.timedelta64(diff,'W')
print(x)

104 weeks


In [ ]:
x = np.timedelta64(diff,'m')
print(x)

1051200 minutes


In [ ]:
x = np.timedelta64(diff,'h')
print(x)

17520 hours


In [ ]:
b=np.datetime64("2024-04-10")-np.datetime64("2004-06-17")
print(b)
k=np.timedelta64(b,"W")
print(k)

7237 days
1033 weeks


In [ ]:
today = np.datetime64("2023-01-20",'m')
print(today)

2023-01-20T00:00


In [ ]:
today = np.datetime64("2023-01-20",'h')
print(today)

2023-01-20T00


In [ ]:
month_date = np.arange('2022-11-25','2022-12-25',dtype = 'datetime64')
print(month_date)

['2022-11-25' '2022-11-26' '2022-11-27' '2022-11-28' '2022-11-29'
 '2022-11-30' '2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04'
 '2022-12-05' '2022-12-06' '2022-12-07' '2022-12-08' '2022-12-09'
 '2022-12-10' '2022-12-11' '2022-12-12' '2022-12-13' '2022-12-14'
 '2022-12-15' '2022-12-16' '2022-12-17' '2022-12-18' '2022-12-19'
 '2022-12-20' '2022-12-21' '2022-12-22' '2022-12-23' '2022-12-24']


In [ ]:
month = np.arange('2020-10-11','2022-10-11',dtype = 'datetime64[M]')
print(month)

['2020-10' '2020-11' '2020-12' '2021-01' '2021-02' '2021-03' '2021-04'
 '2021-05' '2021-06' '2021-07' '2021-08' '2021-09' '2021-10' '2021-11'
 '2021-12' '2022-01' '2022-02' '2022-03' '2022-04' '2022-05' '2022-06'
 '2022-07' '2022-08' '2022-09']


In [ ]:
month = np.arange('2020-10-11','2022-10-11',dtype = 'datetime64[Y]')
print(month)

['2020' '2021']


In [ ]:
month = np.arange('2012-10-11','2022-10-11',dtype = 'datetime64')
print(month)

['2012-10-11' '2012-10-12' '2012-10-13' ... '2022-10-08' '2022-10-09'
 '2022-10-10']


In [ ]:
print(len(month))

3652
