In [2]:
import numpy as np

# arange function
.arange()

In [4]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [6]:
a = np.arange(0,20,2)   #(start,stop,step)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


# linspace function

In [7]:
a = np.linspace(1,12,6)
print(a)

[ 1.   3.2  5.4  7.6  9.8 12. ]


# reshape of matrix
.arange().reshape()

In [ ]:
a = np.arange(1,19).reshape(2,9)
print(a)

# 1 to 19 & 3x3x2
# 3d x 3row x 2 colum

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [11]:
a.reshape(9,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [7]:
a.reshape(2,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [76]:
x = np.arange(1,33,2, dtype="float")
x

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31.])

In [9]:
x.reshape(2,2,2,4)   # 2 matrix x 2 matrix x 2row x 4 col

array([[[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]],


       [[[17., 18., 19., 20.],
         [21., 22., 23., 24.]],

        [[25., 26., 27., 28.],
         [29., 30., 31., 32.]]]])

In [80]:
x = np.arange(0,20).reshape(2,2,5)
print(x)
x.ndim

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


3

# ravel

ravel and flatten are dimension reduction tequnich which convert any dimension it to one dimension.

In [3]:
x = np.arange(1,10).reshape(3,3)    
print(x)
x1 = x.ravel()         # it replace a memory
print(x1)
x[0,0] = 555
print(x)
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[555   2   3]
 [  4   5   6]
 [  7   8   9]]
[555   2   3   4   5   6   7   8   9]


# flatten

In [12]:
x = np.arange(1,10).reshape(3,3)    
print(x)
x1 = x.flatten()          # it create new memory
print(x1)
x[0,0] = 555
print(x)
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[555   2   3]
 [  4   5   6]
 [  7   8   9]]
[1 2 3 4 5 6 7 8 9]


# transpose

In [13]:
a = np.arange(1,5).reshape(2,2)
print(a)

[[1 2]
 [3 4]]


In [14]:
a.T

array([[1, 3],
       [2, 4]])

In [15]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [16]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Mathemetical operation

In [19]:
a = np.arange(11,20).reshape(3,3)
b = np.arange(1,10).reshape(3,3)
print(a)
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(a+b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [21]:
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [22]:
print(a-b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [23]:
np.subtract(a,b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
print(a*b)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [25]:
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [26]:
print(a/b)

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [27]:
np.divide(a,b)

array([[11.        ,  6.        ,  4.33333333],
       [ 3.5       ,  3.        ,  2.66666667],
       [ 2.42857143,  2.25      ,  2.11111111]])

In [28]:
print(a @ b)

[[150 186 222]
 [186 231 276]
 [222 276 330]]


In [29]:
a.dot(b)

array([[150, 186, 222],
       [186, 231, 276],
       [222, 276, 330]])

In [30]:
print(a)
a.sum()

[[11 12 13]
 [14 15 16]
 [17 18 19]]


135

# trignometry

In [31]:
np.sin(0.523599)      # 30 degree = 0.523599 radiant

0.5000001943375613

In [32]:
np.sin(30 * np.pi/180)   # degree convert into radiant

0.49999999999999994

In [33]:
np.cos(60 * np.pi /180)

0.5000000000000001

In [34]:
np.tan(45 * np.pi/180)

0.9999999999999999

# statistic in numpy

In [35]:
x = np.array([[4,8,16],[9,5,3],[1,5,7]])
print(x)

[[ 4  8 16]
 [ 9  5  3]
 [ 1  5  7]]


In [36]:
x.min()

1

In [37]:
x.max()

16

In [38]:
x.mean()

6.444444444444445

In [39]:
x.argmax()  # it return position of first maximum number

2

In [40]:
x.argmin()  # it return position of first minimum number

6

In [17]:
x.argmax(axis = 1)  # raw wise (4 8 16 = pos 2 , 9 5 3 = pos 0 , 1 5 7 = pos 2)  max number

NameError: name 'x' is not defined

In [42]:
x.argmax(axis = 0)  # column wise (4 9 1 = pos 1 , 8 5 5 = pos 0 , 16 3 7 = pos 0)  max number

array([1, 0, 0], dtype=int64)

In [43]:
x.argmin(axis = 1)  # raw wise (4 8 16 = pos 0 , 9 5 3 = pos 2 , 1 5 7 = pos 0)  min number

array([0, 2, 0], dtype=int64)

In [44]:
x.argmin(axis = 0)  # column wise (4 9 1 = pos 2 , 8 5 5 = pos 1 , 16 3 7 = pos 1)  min number

array([2, 1, 1], dtype=int64)

In [45]:
x.std()

4.112612338515944

In [46]:
np.square(x)

array([[ 16,  64, 256],
       [ 81,  25,   9],
       [  1,  25,  49]])

In [47]:
np.sqrt(x)

array([[2.        , 2.82842712, 4.        ],
       [3.        , 2.23606798, 1.73205081],
       [1.        , 2.23606798, 2.64575131]])

In [48]:
a = np.nan
print(a)

nan


In [49]:
np.log(10)

2.302585092994046

In [50]:
np.log10(1000)

3.0

# stacking

In [7]:
a = np.arange(1,10,dtype="int").reshape(3,3)
b = np.arange(11,20,dtype="int").reshape(3,3)
c = np.arange(21,30,dtype="int").reshape(3,3)
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [52]:
x = np.hstack((a,b))
print(x)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [53]:
y = np.hstack((a,b,c))
print(y)

[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]


In [54]:
z = np.vstack((a,b))
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [55]:
d = np.vstack((a,b,c))
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [56]:
e = np.concatenate((a,b,c),axis = 0)    #0 = column
print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [8]:
e = np.concatenate((a,b,c),axis = 1)    #1 = row
print(e)

[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]


In [11]:
z = np.split(e,3)
print(z)

[array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23]]), array([[ 4,  5,  6, 14, 15, 16, 24, 25, 26]]), array([[ 7,  8,  9, 17, 18, 19, 27, 28, 29]])]


In [59]:
type(z)

list

In [60]:
(type(z[0]))

numpy.ndarray

In [61]:
y = np.array([1, 2, 3, 1, 2, 3, 1, 2, 3])
np.split(y,[1,3,5,8])

[array([1]), array([2, 3]), array([1, 2]), array([3, 1, 2]), array([3])]

# creating matrix of desire shape

In [62]:
# (2,4,3)
x = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])
x.shape

(2, 4, 3)

In [63]:
# (1,2,4,3)
x = np.array([[[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]]])
x.shape

(1, 2, 4, 3)

In [64]:
# (1,2,3,4)
x = np.array([[[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
x.shape

(1, 2, 3, 4)

In [65]:
# (2,3,1,3)
x = np.array([[[[1,5,9]],[[1,5,9]],[[1,5,9]]],[[[1,5,9]],[[1,5,9]],[[1,5,9]]]])
x.shape

(2, 3, 1, 3)