# Installation of Numpy

In [1]:
!pip install numpy

In [1]:
import numpy as np

# 1 d array

In [4]:
one = np.array([1,2,3,4])
print(one)

[1 2 3 4]


# 2 d array

In [5]:
two = np.array([[1,2,3],[4,5,6]])
print(two)

[[1 2 3]
 [4 5 6]]


In [6]:
two = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3 d array

In [6]:
three = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(three)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [7]:
three = np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
print(three)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


# find array shape,dimention and size

In [12]:
one = np.array([1,2,3,4,5,6,7,8,9,10])
print(one)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
one.shape #it means (1,10)

(10,)

In [10]:
one.ndim   #1d dimention

1

In [11]:
one.size   # total eliments

10

In [12]:
one.itemsize   # int = 4 bytes , float = 8 bytes

4

In [63]:
one.dtype

dtype('int32')

In [13]:
one1 =  one.astype("float")
one1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [62]:
one1.dtype

dtype('float64')

In [14]:
one1.itemsize

8

In [15]:
two = np.array([[1,2,3],[4,5,6]])
print(two)

[[1 2 3]
 [4 5 6]]


In [16]:
two.shape  # (row,column)

(2, 3)

In [17]:
two.ndim   #2d dimention

2

In [18]:
two.size

6

In [65]:
two.dtype

dtype('int32')

In [19]:
two.itemsize  

4

In [20]:
two1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
two1.shape 

(3, 3)

In [22]:
two1.ndim

2

In [23]:
two1.size

9

In [3]:
three = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


(1, 3, 3)

In [25]:
three.shape

(1, 3, 3)

In [26]:
three.ndim

3

In [27]:
three.size

9

In [28]:
three1 = np.array([[[1,2,3],[4,5,6],[7,8,9,]],[[1,2,3],[4,5,6],[7,8,9]]])
print(three1)
#(2,3,3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
three1.shape

(2, 3, 3)

In [30]:
three1.ndim

3

In [31]:
three1.size

18

In [32]:
three2 = np.array([[[1,2,3],[4,5,6],[7,8,9,]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(three2)
#(3,3,3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [33]:
three2.shape  # count of metrix,row,column

(3, 3, 3)

In [34]:
three2.ndim

3

In [35]:
three2.size

27

In [36]:
three3 = np.array([[[1,2,3,10],[4,5,6,11],[7,8,9,12]],[[1,2,3,10],[4,5,6,11],[7,8,9,12]],[[1,2,3,10],[4,5,6,11],[7,8,9,12]]])
print(three3)

[[[ 1  2  3 10]
  [ 4  5  6 11]
  [ 7  8  9 12]]

 [[ 1  2  3 10]
  [ 4  5  6 11]
  [ 7  8  9 12]]

 [[ 1  2  3 10]
  [ 4  5  6 11]
  [ 7  8  9 12]]]


In [37]:
three3.shape

(3, 3, 4)

In [38]:
three3.ndim

3

In [39]:
three3.size

36

# find data types

In [40]:
print(type(three))

<class 'numpy.ndarray'>


In [41]:
three.dtype

dtype('int32')

# Change datatypes

In [15]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
x.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [43]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
print(x)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [44]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="str")
print(x)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [68]:
x = np.array([[1,2,3],[4,0,0],[7,8,9]],dtype="bool")
print(x)

[[ True  True  True]
 [ True False False]
 [ True  True  True]]


In [71]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
x.dtype

dtype('int32')

# creat ones matrix & change datatypes
.ones

In [3]:
ones = np.ones((2,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
ones = np.ones((3,3),dtype='int')
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [49]:
ones = np.ones((3,3),dtype='float')
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
ones = np.ones((3,3),dtype='str')
print(ones)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [51]:
ones = np.ones((3,3),dtype='bool')
print(ones)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [52]:
ones = np.ones((3,3),dtype='complex')
print(ones)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


# creat zeros matrix & chnage datatypes
.zeros

In [53]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
zeros = np.zeros((3,3),dtype='int')
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
zeros = np.zeros((3,3),dtype='float')
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
zeros = np.zeros((3,3),dtype='str')
print(zeros)

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [57]:
zeros = np.zeros((3,3),dtype='bool')
print(zeros)

[[False False False]
 [False False False]
 [False False False]]


In [58]:
zeros = np.zeros((3,3),dtype='complex')
print(zeros)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


# diaginal matrix
.diag

In [59]:
a = np.diag([1,3,6,2,9])
print(a)

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 6 0 0]
 [0 0 0 2 0]
 [0 0 0 0 9]]


# identity matrix
.eye

In [60]:
a = np.eye(4,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
a = np.eye(3,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
